name: docker image build and push

on:
  push:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          lfs: true
      - name: Build and push to docker
        working-directory: .
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -t fretje/crystalreportsruntime:latest .
          docker image push fretje/crystalreportsruntime:latest
          docker logout
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
