name: docker image build and push

on:
  push:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Build and push console
        working-directory: .
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker build -t fretje/crystalreportsruntime:fromgithub .
          docker image push fretje/crystalreportsruntime:fromgithub
          docker logout
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
